"""
Wiki file loading utilities.

This module provides utilities for loading and parsing wiki markdown files
generated by code-review-graph.
"""

from pathlib import Path
from typing import Dict, List, Optional


class WikiLoader:
    """Loads and parses wiki markdown files."""
    
    def __init__(self, wiki_dir: str):
        """
        Initialize the wiki loader.
        
        Args:
            wiki_dir: Path to the wiki directory
        """
        self.wiki_dir = Path(wiki_dir)
    
    def wiki_exists(self) -> bool:
        """
        Check if wiki directory exists and has content.
        
        Returns:
            True if wiki directory exists and contains markdown files
        """
        return self.wiki_dir.exists() and any(self.wiki_dir.glob("*.md"))
    
    def list_wiki_files(self) -> List[Path]:
        """
        List all markdown files in wiki directory.
        
        Returns:
            List of Path objects for markdown files
        """
        return list(self.wiki_dir.glob("*.md"))
    
    def load_file(self, filename: str) -> Optional[str]:
        """
        Load a specific wiki file.
        
        Args:
            filename: Name of the file to load
            
        Returns:
            File content as string, or None if file doesn't exist
        """
        path = self.wiki_dir / filename
        if path.exists():
            return path.read_text(encoding="utf-8")
        return None
    
    def load_all(self) -> Dict[str, str]:
        """
        Load all wiki files into a dictionary.
        
        Returns:
            Dictionary mapping filename to content
        """
        wiki_content = {}
        for file_path in self.list_wiki_files():
            wiki_content[file_path.name] = file_path.read_text(encoding="utf-8")
        return wiki_content
    
    def get_mtime(self) -> float:
        """
        Get the most recent modification time of wiki files.
        
        Returns:
            Timestamp of most recently modified file, or 0 if no files
        """
        mtimes = [f.stat().st_mtime for f in self.list_wiki_files()]
        return max(mtimes) if mtimes else 0
    
    def get_file_count(self) -> int:
        """
        Get the number of wiki files.
        
        Returns:
            Number of markdown files in wiki directory
        """
        return len(self.list_wiki_files())
    
    def get_total_size(self) -> int:
        """
        Get the total size of all wiki files in bytes.
        
        Returns:
            Total size in bytes
        """
        total = 0
        for file_path in self.list_wiki_files():
            try:
                total += file_path.stat().st_size
            except Exception:
                continue
        return total
